name: pr

on:
  push:
    branches-ignore:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create PR
      uses: funivan/github-autopr@0.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: .head_commit.message
