name: tests

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: install brew
        run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      - name: install packages
        run: brew install coreutils findutils jq
      - name: run the tests
        run: find ./tests -type f -not -name '*.swp' | xargs -n1 bash -x
        env:
          PATH: "/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/findutils/libexec/gnubin:/usr/local/bin:/bin:/usr/bin"
